import "./globals.css";
import { fonts } from "@verno/design-system/lib/fonts";
import { DesignSystemProvider } from "@verno/design-system/components/providers/client";
import type { Metadata } from "next";
import type { ReactNode } from "react";

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

interface RootLayoutProps {
  readonly children: ReactNode;
}

const RootLayout = ({ children }: RootLayoutProps) => (
  <html lang="en" suppressHydrationWarning>
    <body className={fonts}>
      <DesignSystemProvider>
        <main className="relative z-10 mx-auto grid w-full max-w-2xl gap-16 sm:gap-24 px-4 py-16 sm:py-32">
          {children}
        </main>
      </DesignSystemProvider>
    </body>
  </html>
);

export default RootLayout;
