/* eslint-disable max-lines */
/* This file is generated by scripts/generate-template-registry.ts — do not edit by hand. */

export const TEMPLATE_COUNT = 20 as const;

export const EMBEDDED_BY_LAYER = {
  "shared": new Map<string, string>([
    [".editorconfig", `root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
`],
    [".gitignore", `# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.

# dependencies
node_modules
/.pnp
.pnp.*
.yarn/*
!.yarn/patches
!.yarn/plugins
!.yarn/releases
!.yarn/versions

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.pnpm-debug.log*

# env files (can opt-in for committing if needed)
.env*

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts

# Turborepo
.turbo

# Dist
dist

# Next.js
.next`],
    ["README.md", `# {{projectName}}

─ Verno{{#if turborepo}} · Turborepo{{/if}} · Next.js · @{{npmScope}}

## Structure

{{#if turborepo}}
\`\`\`
{{projectName}}
{{#if hasTypescriptConfigPackage}}
├── apps/web
└── packages/{{tsConfigName}}
{{else}}
└── apps/web
{{/if}}
\`\`\`
{{else}}
\`\`\`
{{projectName}}
{{#if useShadcn}}
├── app/
├── package.json
└── components.json
{{else}}
├── app/
└── package.json
{{/if}}
\`\`\`
{{/if}}

## Links

- [Verno Studio](https://github.com/verno-studio/website)
{{#if useShadcn}}
- [shadcn/ui](https://ui.shadcn.com/docs)
{{/if}}
{{#if turborepo}}
- [Turborepo](https://turborepo.dev/docs)
{{/if}}

## Develop

{{#if turborepo}}From the repo root:

{{/if}}
\`\`\`bash
{{devCommand}}
\`\`\`
`]
  ]),
  "frontends/next": new Map<string, string>([
    ["app/globals.css", `@import "tailwindcss";
{{#if useShadcn}}
/* This layer is by Verno Studio */
@layer base {
  *,
  ::after,
  ::before,
  ::backdrop,
  ::file-selector-button {
    @apply border-border;
  }
  ::selection {
    @apply bg-foreground text-background;
  }
  html {
    font-feature-settings:
      "rlig" 1,
      "calt" 0,
      "ss11" 1;
    font-kerning: normal;
    font-optical-sizing: auto;
    font-synthesis: none;
    text-rendering: optimizeLegibility;
    -webkit-font-smoothing: antialiased;
    scroll-behavior: smooth;
  }
  body {
    @apply min-h-dvh;
    @apply bg-background text-foreground;
  }
  h1,
  h2,
  h3,
  h4,
  h5,
  h6 {
    @apply text-foreground;
    font-weight: var(--font-weight-heading, 450);
    text-wrap: balance;
  }
  /* Prose stays near 60-68 characters; rewrite before shrinking. */
  h1 {
    @apply max-w-[24ch] text-4xl;
  }
  h2 {
    @apply text-2xl;
  }
  h3 {
    @apply text-xl;
  }
  h4,
  h5,
  h6 {
    @apply text-base;
    letter-spacing: var(--tracking-snug, -0.02em);
  }
  p {
    text-wrap: pretty;
  }
  /* Links inherit their color and carry a quiet rule that firms up on hover. */
  a {
    color: inherit;
    text-decoration-color: var(--border);
    text-decoration-thickness: 1px;
    text-underline-offset: 3px;
  }
  a:hover {
    text-decoration-color: currentColor;
  }
  code,
  kbd,
  samp,
  pre {
    @apply font-mono;
  }
  input::placeholder,
  textarea::placeholder {
    color: var(--muted-foreground);
  }
  button:not(:disabled),
  [role="button"]:not(:disabled) {
    @apply cursor-pointer;
  }
  a:focus-visible,
  button:focus-visible,
  input:focus-visible,
  select:focus-visible,
  summary:focus-visible,
  textarea:focus-visible {
    outline: 2px solid var(--ring);
    outline-offset: 3px;
  }
  a[target="_blank"],
  a[target="_blank"] *,
  a[href^="mailto:"],
  a[href^="mailto:"] * {
    @apply cursor-alias;
  }
  @media (prefers-reduced-motion: reduce) {
    *,
    *::before,
    *::after {
      animation-duration: 0.01ms !important;
      animation-iteration-count: 1 !important;
      scroll-behavior: auto !important;
      transition-duration: 0.01ms !important;
    }
  }
}
{{/if}}
`],
    ["app/layout.tsx", `import "./globals.css";
{{#if useShadcn}}
import type { Metadata } from "next";
import { DesignSystemProvider } from "@/components/providers/client";
import { fonts } from "@/lib/fonts";
import type { ReactNode } from "react";
{{else}}
import type { Metadata } from "next";
import type { ReactNode } from "react";
{{/if}}

const title = "{{projectName}}";

export const metadata: Metadata = { description: "Next.js app", title };

interface RootLayoutProps {
  readonly children: ReactNode;
}

const RootLayout = ({ children }: RootLayoutProps) =>
{{#if useShadcn}}
(
  <html lang="en" suppressHydrationWarning>
    <body className={fonts}>
      <DesignSystemProvider>{children}</DesignSystemProvider>
    </body>
  </html>
);
{{else}}
(
  <html lang="en" suppressHydrationWarning>
    <body className="min-h-dvh antialiased">{children}</body>
  </html>
);
{{/if}}

export default RootLayout;
`],
    ["app/page.tsx", `const Home = () => (
  <main className="mx-auto flex min-h-dvh w-full max-w-2xl flex-col px-6 py-24 sm:py-32">
    <section className="grid gap-24">
      <header>
        <h1 className="font-serif text-3xl font-normal tracking-tight text-foreground sm:text-5xl">
          {{ projectName }}
        </h1>
        <p className="mt-1 text-muted-foreground">A Verno Studio starter.</p>
      </header>
      <div className="grid gap-5 text-pretty text-sm leading-7 text-muted-foreground sm:text-base">
        <p>
          A Verno Studio starter, shaped for taste, systems, and the first commit—so the surface is
          considered before the feature list runs long.
        </p>
        <p>
          Edit{" "}
          <code className="rounded border border-border bg-muted px-1.5 py-0.5 font-mono text-sm text-foreground">
            app/page.tsx
          </code>{" "}
          to get started.
        </p>
      </div>
    </section>
  </main>
);

export default Home;
`],
    ["components.json", `{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "{{componentsStyle}}",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "",
    "css": "app/globals.css",
    "baseColor": "neutral",
    "cssVariables": true,
    "prefix": ""
  },
  "iconLibrary": "lucide",
  "rtl": false,
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils",
    "ui": "@/components/ui",
    "lib": "@/lib",
    "hooks": "@/hooks"
  },
  "menuColor": "default",
  "menuAccent": "subtle",
  "registries": {
    "@vernostudio": "https://verno-studio.vercel.app/r/{name}.json"
  }
}
`],
    ["components/providers/client.tsx", `"use client";

import { ThemeProvider } from "next-themes";
import type { PropsWithChildren } from "react";

// Depends on nothing but next-themes, which is a real package. Wrapping in
// \`TooltipProvider\` or rendering a \`<Toaster />\` here would import
// components/ui files that do not exist until \`shadcn add tooltip sonner\` has
// run — add them once you have.
export const DesignSystemProvider = ({ children }: PropsWithChildren) => (
  <ThemeProvider attribute="class" defaultTheme="system" disableTransitionOnChange enableSystem>
    {children}
  </ThemeProvider>
);
`],
    ["lib/fonts.ts", `import { cn } from "./utils";
import {
  Geist as createSans,
  Instrument_Serif as createSerif,
  Geist_Mono as createMono,
} from "next/font/google";

const sans = createSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const mono = createMono({
  subsets: ["latin"],
  variable: "--font-mono",
});

const serif = createSerif({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-serif",
  weight: "400",
});

export const fonts = cn(
  sans.variable,
  mono.variable,
  serif.variable,
  "touch-manipulation font-sans antialiased",
);
`],
    ["lib/utils.ts", `export { cn } from "cnfast";
`],
    ["next.config.ts", `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    formats: ["image/avif", "image/webp"],
  },
};

export default nextConfig;
`],
    ["package.json", `{
  "name": "{{#if turborepo}}web{{else}}{{projectName}}{{/if}}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "next build",
    "dev": "next dev{{#if turborepo}} --port 3000{{/if}}",
    "start": "next start",
    "typecheck": "next typegen && tsc --noEmit"
  },
  "dependencies": {},
{{#if turborepo}}
  "devDependencies": {}
{{else}}
  "devDependencies": {},
  "packageManager": "{{packageManagerField}}"
{{/if}}
}
`],
    ["postcss.config.mjs", `const config = { plugins: { "@tailwindcss/postcss": {} } };
export default config;
`],
    ["tsconfig.json", `{{#if turborepo}}
  {{#if hasTypescriptConfigPackage}}
    { "extends": "../../packages/typescript-config/nextjs.json", "compilerOptions": { "paths": {
    "@/*": ["./*"], "@{{npmScope}}/*": ["../../packages/*"] } }, "include": [ "next-env.d.ts",
    "**/*.ts", "**/*.tsx", ".next/types/**/*.ts", ".next/dev/types/**/*.ts" ], "exclude":
    ["node_modules"] }
  {{else}}
    { "compilerOptions": { "target": "ES2017", "lib": ["dom", "dom.iterable", "esnext"], "allowJs":
    true, "skipLibCheck": true, "strict": true, "esModuleInterop": true, "module":
    "esnext", "moduleResolution": "bundler", "resolveJsonModule": true, "isolatedModules": true,
    "jsx": "react-jsx", "incremental": true, "plugins": [{ "name": "next" }], "paths": { "@/*":
    ["./*"] } }, "include": [ "next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts",
    ".next/dev/types/**/*.ts" ], "exclude": ["node_modules"] }
  {{/if}}
{{else}}
  { "compilerOptions": { "target": "ES2017", "lib": ["dom", "dom.iterable", "esnext"], "allowJs":
  true, "skipLibCheck": true, "strict": true, "esModuleInterop": true, "module":
  "esnext", "moduleResolution": "bundler", "resolveJsonModule": true, "isolatedModules": true,
  "jsx": "react-jsx", "incremental": true, "plugins": [{ "name": "next" }], "paths": { "@/*":
  ["./*"] } }, "include": [ "next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts",
  ".next/dev/types/**/*.ts" ], "exclude": ["node_modules"] }
{{/if}}`]
  ]),
  "addons/turborepo": new Map<string, string>([
    ["package.json", `{
  "name": "{{projectName}}",
  "private": true,
  "workspaces": ["apps/*", "packages/*"],
  "type": "module",
  "scripts": {
    "build": "turbo run build",
    "dev": "turbo run dev",
    "typecheck": "turbo run typecheck"
  },
  "devDependencies": {},
  "engines": {
    "node": ">=18"
  },
  "packageManager": "{{packageManagerField}}"
}
`],
    ["turbo.json", `{
  "$schema": "https://turborepo.dev/schema.json",
  "tasks": {
    "build": {
      "dependsOn": ["^build"],
      "inputs": ["$TURBO_DEFAULT$", ".env*"],
      "outputs": [".next/**", "!.next/cache/**", "dist/**"]
    },
    "typecheck": { "dependsOn": ["^typecheck"] },
    "dev": { "cache": false, "persistent": true }
  }
}
`]
  ]),
  "packages/typescript-config": new Map<string, string>([
    ["packages/typescript-config/base.json", `{
  "$schema": "https://json.schemastore.org/tsconfig",
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "strictNullChecks": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "incremental": true
  },
  "exclude": ["node_modules"]
}
`],
    ["packages/typescript-config/nextjs.json", `{
  "$schema": "https://json.schemastore.org/tsconfig",
  "extends": "./base.json",
  "compilerOptions": {
    "plugins": [{ "name": "next" }]
  }
}
`],
    ["packages/typescript-config/package.json", `{
  "name": "{{tsConfigName}}",
  "version": "0.0.0",
  "private": true,
  "license": "MIT",
  "files": [
    "base.json",
    "nextjs.json",
    "react-library.json"
  ]
}
`],
    ["packages/typescript-config/react-library.json", `{
  "$schema": "https://json.schemastore.org/tsconfig",
  "extends": "./base.json",
  "compilerOptions": { "jsx": "react-jsx" }
}
`]
  ])
} as const satisfies Record<string, ReadonlyMap<string, string>>;

