/* eslint-disable max-lines */
/* This file is generated by scripts/generate-template-registry.ts — do not edit by hand. */

export const TEMPLATE_COUNT = 32 as const;

export const EMBEDDED_BY_LAYER = {
  "next-app": new Map<string, string>([
    [
      "app/globals.css",
      `@import "tailwindcss";
`,
    ],
    [
      "app/layout.tsx",
      `import "./globals.css";
import type { Metadata } from "next";
import type { ReactNode } from "react";

const title = "{{projectName}}";

export const metadata: Metadata = { description: "Next.js app", title };

const RootLayout = ({ children }: { readonly children: ReactNode }) => (
  <html lang="en" suppressHydrationWarning>
    <body className="antialiased min-h-dvh">{children}</body>
  </html>
);

export default RootLayout;
`,
    ],
    [
      "app/page.tsx",
      `const Home = () => (
  <main className="mx-auto flex min-h-dvh max-w-2xl flex-col justify-center gap-4 px-4 py-16">
    <h1 className="text-3xl font-semibold tracking-tight">{{ projectName }}</h1>
    <p className="text-neutral-600">
      Edit{" "}
      <code className="rounded bg-neutral-100 px-1.5 py-0.5 text-sm dark:bg-neutral-800">
        app/page.tsx
      </code>{" "}
      to get started.
    </p>
  </main>
);

export default Home;
`,
    ],
    [
      "next-env.d.ts",
      `/// <reference types="next" />
/// <reference types="next/image-types/global" />
`,
    ],
    [
      "next.config.ts",
      `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: { formats: ["image/avif", "image/webp"] },
};

export default nextConfig;
`,
    ],
    [
      "package.json",
      `{
  "name": "{{projectName}}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "next build",
    "dev": "next dev --port 3000",
    "format": "ultracite fix",
    "lint": "ultracite check",
    "start": "next start",
    "typecheck": "tsc --noEmit"
  },
  "dependencies": {},
  "devDependencies": {},
  "packageManager": "{{packageManagerField}}"
}
`,
    ],
    [
      "postcss.config.mjs",
      `const config = { plugins: { "@tailwindcss/postcss": {} } };
export default config;
`,
    ],
    [
      "README.md",
      `# {{projectName}}

Next.js app (Verno \`next-app\`). npm scope: \`@{{npmScope}}\`.

If you skipped steps during \`verno create\`, run \`shadcn\` and \`ultracite\` in this directory.

To apply a different shadcn preset on an existing project: \`<package runner> shadcn@latest apply --preset <code>\` (see [shadcn CLI](https://ui.shadcn.com/docs/cli)).
`,
    ],
    [
      "tsconfig.json",
      `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    ".next/types/**/*.ts",
    ".next/dev/types/**/*.ts"
  ],
  "exclude": ["node_modules"]
}
`,
    ],
  ]),
  "next-turborepo": new Map<string, string>([
    [
      "apps/web/app/globals.css",
      `@import "tailwindcss";
@import "{{dsName}}/styles/globals.css";
`,
    ],
    [
      "apps/web/app/layout.tsx",
      `import "./globals.css";
import type { Metadata } from "next";
import type { ReactNode } from "react";

const title = "{{projectName}}";

export const metadata: Metadata = { description: "Next.js app", title };

const RootLayout = ({ children }: { readonly children: ReactNode }) => (
  <html lang="en" suppressHydrationWarning>
    <body className="antialiased min-h-dvh">{children}</body>
  </html>
);

export default RootLayout;
`,
    ],
    [
      "apps/web/app/page.tsx",
      `const Home = () => (
  <main className="mx-auto flex min-h-dvh max-w-2xl flex-col justify-center gap-4 px-4 py-16">
    <h1 className="text-3xl font-semibold tracking-tight">{{ projectName }}</h1>
    <p className="text-neutral-600">
      Edit{" "}
      <code className="rounded bg-neutral-100 px-1.5 py-0.5 text-sm dark:bg-neutral-800">
        app/page.tsx
      </code>{" "}
      to get started.
    </p>
  </main>
);

export default Home;
`,
    ],
    [
      "apps/web/next-env.d.ts",
      `/// <reference types="next" />
/// <reference types="next/image-types/global" />
`,
    ],
    [
      "apps/web/next.config.ts",
      `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: { formats: ["image/avif", "image/webp"] },
  transpilePackages: ["{{dsName}}"],
};

export default nextConfig;
`,
    ],
    [
      "apps/web/package.json",
      `{
  "name": "web",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "next build",
    "dev": "next dev --port 3000",
    "start": "next start",
    "typecheck": "tsc --noEmit"
  },
  "dependencies": {
    "{{dsName}}": "workspace:*"
  },
  "devDependencies": {}
}
`,
    ],
    [
      "apps/web/postcss.config.mjs",
      `const config = { plugins: { "@tailwindcss/postcss": {} } };
export default config;
`,
    ],
    [
      "apps/web/tsconfig.json",
      `{
  "extends": "../../packages/typescript-config/nextjs.json",
  "compilerOptions": {
    "paths": {
      "@/*": ["./*"],
      "@{{npmScope}}/*": ["../../packages/*"]
    }
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    ".next/types/**/*.ts",
    ".next/dev/types/**/*.ts"
  ],
  "exclude": ["node_modules"]
}
`,
    ],
    [
      "package.json",
      `{
  "name": "{{projectName}}",
  "private": true,
  "workspaces": [
    "apps/*",
    "packages/*"
  ],
  "type": "module",
  "scripts": {
    "build": "turbo run build",
    "dev": "turbo run dev",
    "format": "ultracite fix",
    "lint": "ultracite check",
    "typecheck": "turbo run typecheck"
  },
  "devDependencies": {},
  "engines": {
    "node": ">=18"
  },
  "packageManager": "{{packageManagerField}}"
}
`,
    ],
    [
      "README.md",
      `# {{projectName}}

Turborepo + Next.js (Verno \`next-turborepo\`).

Packages: \`{{dsName}}\`, \`{{tsConfigName}}\`.

Post-create (if skipped during \`verno create\`): \`shadcn\` and \`ultracite\` via \`@verno/cli\`.

To switch the shadcn design-system preset later, from the repo root:

\`cd packages/design-system && <package runner> shadcn@latest apply --preset <code>\`

Example (pnpm): \`cd packages/design-system && pnpm dlx shadcn@latest apply --preset <code>\`
`,
    ],
    [
      "turbo.json",
      `{
  "$schema": "https://turborepo.dev/schema.json",
  "tasks": {
    "build": {
      "dependsOn": ["^build"],
      "inputs": ["$TURBO_DEFAULT$", ".env*"],
      "outputs": [".next/**", "!.next/cache/**", "dist/**"]
    },
    "typecheck": { "dependsOn": ["^typecheck"] },
    "dev": { "cache": false, "persistent": true }
  }
}
`,
    ],
  ]),
  "packages/design-system": new Map<string, string>([
    [
      "packages/design-system/components.json",
      `{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "{{componentsStyle}}",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "",
    "css": "styles/globals.css",
    "baseColor": "neutral",
    "cssVariables": true,
    "prefix": ""
  },
  "iconLibrary": "lucide",
  "rtl": false,
  "aliases": {
    "components": "{{dsName}}/components",
    "utils": "{{dsName}}/lib/utils",
    "ui": "{{dsName}}/components/ui",
    "lib": "{{dsName}}/lib",
    "hooks": "{{dsName}}/hooks"
  },
  "menuColor": "default",
  "menuAccent": "subtle",
  "registries": {}
}
`,
    ],
    [
      "packages/design-system/lib/utils.ts",
      `import { clsx } from "clsx";
import type { ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export const cn = (...inputs: ClassValue[]) => twMerge(clsx(inputs));
`,
    ],
    [
      "packages/design-system/package.json",
      `{
  "name": "{{dsName}}",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "sideEffects": false,
  "scripts": {
    "typecheck": "tsc --noEmit"
  },
  "dependencies": {},
  "devDependencies": {},
  "peerDependencies": {}
}
`,
    ],
    [
      "packages/design-system/src/index.ts",
      `export { cn } from "../lib/utils";
`,
    ],
    [
      "packages/design-system/styles/globals.css",
      `@import "tailwindcss";
@import "tw-animate-css";
@import "shadcn/tailwind.css";

@custom-variant dark (&:is(.dark *));

@source "../../../**/*.{ts,tsx}";

@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --color-sidebar-ring: var(--sidebar-ring);
  --color-sidebar-border: var(--sidebar-border);
  --color-sidebar-accent-foreground: var(--sidebar-accent-foreground);
  --color-sidebar-accent: var(--sidebar-accent);
  --color-sidebar-primary-foreground: var(--sidebar-primary-foreground);
  --color-sidebar-primary: var(--sidebar-primary);
  --color-sidebar-foreground: var(--sidebar-foreground);
  --color-sidebar: var(--sidebar);
  --color-chart-5: var(--chart-5);
  --color-chart-4: var(--chart-4);
  --color-chart-3: var(--chart-3);
  --color-chart-2: var(--chart-2);
  --color-chart-1: var(--chart-1);
  --color-ring: var(--ring);
  --color-input: var(--input);
  --color-border: var(--border);
  --color-destructive: var(--destructive);
  --color-destructive-foreground: var(--destructive-foreground);
  --color-accent-foreground: var(--accent-foreground);
  --color-accent: var(--accent);
  --color-muted-foreground: var(--muted-foreground);
  --color-muted: var(--muted);
  --color-secondary-foreground: var(--secondary-foreground);
  --color-secondary: var(--secondary);
  --color-primary-foreground: var(--primary-foreground);
  --color-primary: var(--primary);
  --color-popover-foreground: var(--popover-foreground);
  --color-popover: var(--popover);
  --color-card-foreground: var(--card-foreground);
  --color-card: var(--card);
  --radius-sm: calc(var(--radius) - 4px);
  --radius-md: calc(var(--radius) - 2px);
  --radius-lg: var(--radius);
  --radius-xl: calc(var(--radius) + 4px);
  --shadow-2xs: var(--shadow-2xs);
  --shadow-xs: var(--shadow-xs);
  --shadow-sm: var(--shadow-sm);
  --shadow: var(--shadow);
  --shadow-md: var(--shadow-md);
  --shadow-lg: var(--shadow-lg);
  --shadow-xl: var(--shadow-xl);
  --shadow-2xl: var(--shadow-2xl);
}

:root,
.light {
  --background: oklch(0.99 0 0);
  --foreground: oklch(0 0 0);
  --card: oklch(1 0 0);
  --card-foreground: oklch(0 0 0);
  --popover: oklch(0.99 0 0);
  --popover-foreground: oklch(0 0 0);
  --primary: oklch(0 0 0);
  --primary-foreground: oklch(1 0 0);
  --secondary: oklch(0.94 0 0);
  --secondary-foreground: oklch(0 0 0);
  --muted: oklch(0.97 0 0);
  --muted-foreground: oklch(0.44 0 0);
  --accent: oklch(0.94 0 0);
  --accent-foreground: oklch(0 0 0);
  --destructive: oklch(0.63 0.19 23.03);
  --destructive-foreground: oklch(1 0 0);
  --border: oklch(0.92 0 0);
  --input: oklch(0.94 0 0);
  --ring: oklch(0 0 0);
  --chart-1: oklch(0.81 0.17 75.35);
  --chart-2: oklch(0.55 0.22 264.53);
  --chart-3: oklch(0.72 0 0);
  --chart-4: oklch(0.92 0 0);
  --chart-5: oklch(0.56 0 0);
  --sidebar: oklch(0.99 0 0);
  --sidebar-foreground: oklch(0 0 0);
  --sidebar-primary: oklch(0 0 0);
  --sidebar-primary-foreground: oklch(1 0 0);
  --sidebar-accent: oklch(0.94 0 0);
  --sidebar-accent-foreground: oklch(0 0 0);
  --sidebar-border: oklch(0.94 0 0);
  --sidebar-ring: oklch(0 0 0);
  --radius: 0rem;
  --shadow-2xs: 0px 1px 2px 0px hsl(0 0% 0% / 0.09);
  --shadow-xs: 0px 1px 2px 0px hsl(0 0% 0% / 0.09);
  --shadow-sm: 0px 1px 2px 0px hsl(0 0% 0% / 0.18), 0px 1px 2px -1px hsl(0 0% 0% / 0.18);
  --shadow: 0px 1px 2px 0px hsl(0 0% 0% / 0.18), 0px 1px 2px -1px hsl(0 0% 0% / 0.18);
  --shadow-md: 0px 1px 2px 0px hsl(0 0% 0% / 0.18), 0px 2px 4px -1px hsl(0 0% 0% / 0.18);
  --shadow-lg: 0px 1px 2px 0px hsl(0 0% 0% / 0.18), 0px 4px 6px -1px hsl(0 0% 0% / 0.18);
  --shadow-xl: 0px 1px 2px 0px hsl(0 0% 0% / 0.18), 0px 8px 10px -1px hsl(0 0% 0% / 0.18);
  --shadow-2xl: 0px 1px 2px 0px hsl(0 0% 0% / 0.45);
  --tracking-normal: 0em;
  --spacing: 0.25rem;
}

.dark {
  --background: oklch(0 0 0);
  --foreground: oklch(1 0 0);
  --card: oklch(0.14 0 0);
  --card-foreground: oklch(1 0 0);
  --popover: oklch(0.18 0 0);
  --popover-foreground: oklch(1 0 0);
  --primary: oklch(1 0 0);
  --primary-foreground: oklch(0 0 0);
  --secondary: oklch(0.25 0 0);
  --secondary-foreground: oklch(1 0 0);
  --muted: oklch(0.23 0 0);
  --muted-foreground: oklch(0.72 0 0);
  --accent: oklch(0.32 0 0);
  --accent-foreground: oklch(1 0 0);
  --destructive: oklch(0.69 0.2 23.91);
  --destructive-foreground: oklch(0 0 0);
  --border: oklch(0.26 0 0);
  --input: oklch(0.32 0 0);
  --ring: oklch(0.72 0 0);
  --chart-1: oklch(0.81 0.17 75.35);
  --chart-2: oklch(0.58 0.21 260.84);
  --chart-3: oklch(0.56 0 0);
  --chart-4: oklch(0.44 0 0);
  --chart-5: oklch(0.92 0 0);
  --sidebar: oklch(0.18 0 0);
  --sidebar-foreground: oklch(1 0 0);
  --sidebar-primary: oklch(1 0 0);
  --sidebar-primary-foreground: oklch(0 0 0);
  --sidebar-accent: oklch(0.32 0 0);
  --sidebar-accent-foreground: oklch(1 0 0);
  --sidebar-border: oklch(0.32 0 0);
  --sidebar-ring: oklch(0.72 0 0);
}

@layer base {
  ::after,
  ::before,
  ::backdrop,
  ::file-selector-button {
    @apply border-border;
  }
  ::selection {
    @apply bg-primary text-background;
  }
  * {
    @apply border-border outline-ring/50;
  }
  html {
    font-feature-settings: "ss01";
    text-rendering: optimizelegibility;
  }
  body {
    @apply min-h-dvh;
    @apply bg-background text-foreground;
  }
  input::placeholder,
  textarea::placeholder {
    @apply text-muted-foreground;
  }
  button:not(:disabled),
  [role="button"]:not(:disabled) {
    @apply cursor-pointer;
  }
  a[target="_blank"],
  a[target="_blank"] *,
  a[href^="mailto:"],
  a[href^="mailto:"] * {
    @apply cursor-alias;
  }
  button:focus,
  input:focus,
  textarea:focus,
  a:focus {
    @apply focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-background;
  }
  @media (prefers-reduced-motion: reduce) {
    *,
    *::before,
    *::after {
      animation-duration: 0.01ms !important;
      animation-iteration-count: 1 !important;
      scroll-behavior: auto !important;
      transition-duration: 0.01ms !important;
    }
  }
}
`,
    ],
    [
      "packages/design-system/tsconfig.json",
      `{
  "extends": "../typescript-config/react-library.json",
  "compilerOptions": {
    "paths": {
      "@/*": ["./*"],
      "{{dsName}}/*": ["./*"]
    }
  },
  "include": [
    "components/**/*.ts",
    "components/**/*.tsx",
    "lib/**/*.ts",
    "hooks/**/*.ts",
    "src/**/*.ts",
    "src/**/*.tsx"
  ],
  "exclude": ["node_modules"]
}
`,
    ],
  ]),
  "packages/typescript-config": new Map<string, string>([
    [
      "packages/typescript-config/base.json",
      `{
  "$schema": "https://json.schemastore.org/tsconfig",
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "strictNullChecks": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "incremental": true
  },
  "exclude": ["node_modules"]
}
`,
    ],
    [
      "packages/typescript-config/nextjs.json",
      `{
  "$schema": "https://json.schemastore.org/tsconfig",
  "extends": "./base.json",
  "compilerOptions": {
    "plugins": [{ "name": "next" }]
  }
}
`,
    ],
    [
      "packages/typescript-config/package.json",
      `{
  "name": "{{tsConfigName}}",
  "version": "0.0.0",
  "private": true,
  "license": "MIT",
  "files": [
    "base.json",
    "nextjs.json",
    "react-library.json"
  ]
}
`,
    ],
    [
      "packages/typescript-config/react-library.json",
      `{
  "$schema": "https://json.schemastore.org/tsconfig",
  "extends": "./base.json",
  "compilerOptions": { "jsx": "react-jsx" }
}
`,
    ],
  ]),
  shared: new Map<string, string>([
    [
      ".editorconfig",
      `root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
`,
    ],
    [
      ".gitignore",
      `node_modules
.next
out
.turbo
dist
.env
.env*.local
.DS_Store
*.tsbuildinfo
`,
    ],
  ]),
} as const satisfies Record<string, ReadonlyMap<string, string>>;
