/* eslint-disable max-lines */
/* This file is generated by scripts/generate-template-registry.ts — do not edit by hand. */

export const TEMPLATE_COUNT = 27 as const;

export const EMBEDDED_BY_LAYER = {
  "shared": new Map<string, string>([
    [".editorconfig", `root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
`],
    [".gitignore", `# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.

# dependencies
node_modules
/.pnp
.pnp.*
.yarn/*
!.yarn/patches
!.yarn/plugins
!.yarn/releases
!.yarn/versions

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.pnpm-debug.log*

# env files (can opt-in for committing if needed)
.env*

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts

# Turborepo
.turbo

# Dist
dist

# Next.js
.next`],
    ["README.md", `# {{projectName}}

─ Verno{{#if turborepo}} · Turborepo{{/if}} · Next.js · @{{npmScope}}

## Structure

{{#if turborepo}}
\`\`\`
{{projectName}}
{{#if hasTypescriptConfigPackage}}
{{#if hasDesignSystem}}
├── apps/web
├── packages/{{tsConfigName}}
└── packages/{{dsName}}
{{else}}
├── apps/web
└── packages/{{tsConfigName}}
{{/if}}
{{else if hasDesignSystem}}
├── apps/web
└── packages/{{dsName}}
{{else}}
└── apps/web
{{/if}}
\`\`\`
{{else}}
\`\`\`
{{projectName}}
{{#if useShadcn}}
├── app/
├── package.json
└── components.json
{{else}}
├── app/
└── package.json
{{/if}}
\`\`\`
{{/if}}

## Links

- [Verno Studio](https://github.com/verno-studio/website)
{{#if useShadcn}}
- [shadcn/ui](https://ui.shadcn.com/docs)
{{/if}}
{{#if turborepo}}
- [Turborepo](https://turborepo.dev/docs)
{{/if}}

## Develop

{{#if turborepo}}From the repo root:

{{/if}}
\`\`\`bash
{{devCommand}}
\`\`\`
`]
  ]),
  "frontends/next": new Map<string, string>([
    ["app/globals.css", `@import "tailwindcss";
{{#if hasDesignSystem}}
@import "{{dsName}}/styles/globals.css";
{{/if}}
{{#if hasStyleContract}}
/* This layer is by Verno Studio */
@layer base {
  *,
  ::after,
  ::before,
  ::backdrop,
  ::file-selector-button {
    @apply border-border;
  }
  ::selection {
    @apply bg-foreground text-background;
  }
  html {
    font-feature-settings:
      "rlig" 1,
      "calt" 0,
      "ss11" 1;
    font-kerning: normal;
    font-optical-sizing: auto;
    font-synthesis: none;
    text-rendering: optimizeLegibility;
    -webkit-font-smoothing: antialiased;
    scroll-behavior: smooth;
  }
  body {
    @apply min-h-dvh;
    @apply bg-background text-foreground;
  }
  h1,
  h2,
  h3,
  h4,
  h5,
  h6 {
    @apply text-foreground;
    font-weight: var(--font-weight-heading, 450);
    text-wrap: balance;
  }
  /* Prose stays near 60-68 characters; rewrite before shrinking. */
  h1 {
    @apply max-w-[24ch] text-4xl;
  }
  h2 {
    @apply text-2xl;
  }
  h3 {
    @apply text-xl;
  }
  h4,
  h5,
  h6 {
    @apply text-base;
    letter-spacing: var(--tracking-snug, -0.02em);
  }
  p {
    text-wrap: pretty;
  }
  /* Links inherit their color and carry a quiet rule that firms up on hover. */
  a {
    color: inherit;
    text-decoration-color: var(--border);
    text-decoration-thickness: 1px;
    text-underline-offset: 3px;
  }
  a:hover {
    text-decoration-color: currentColor;
  }
  code,
  kbd,
  samp,
  pre {
    @apply font-mono;
  }
  input::placeholder,
  textarea::placeholder {
    color: var(--muted-foreground);
  }
  button:not(:disabled),
  [role="button"]:not(:disabled) {
    @apply cursor-pointer;
  }
  a:focus-visible,
  button:focus-visible,
  input:focus-visible,
  select:focus-visible,
  summary:focus-visible,
  textarea:focus-visible {
    outline: 2px solid var(--ring);
    outline-offset: 3px;
  }
  a[target="_blank"],
  a[target="_blank"] *,
  a[href^="mailto:"],
  a[href^="mailto:"] * {
    @apply cursor-alias;
  }
  @media (prefers-reduced-motion: reduce) {
    *,
    *::before,
    *::after {
      animation-duration: 0.01ms !important;
      animation-iteration-count: 1 !important;
      scroll-behavior: auto !important;
      transition-duration: 0.01ms !important;
    }
  }
}
{{/if}}
`],
    ["app/layout.tsx", `import "./globals.css";
{{#if useShadcn}}
import type { Metadata } from "next";
{{#if hasDesignSystem}}
import { DesignSystemProvider } from "{{dsName}}/components/providers/client";
import { fonts } from "{{dsName}}/lib/fonts";
{{else}}
import { DesignSystemProvider } from "@/components/providers/client";
import { fonts } from "@/lib/fonts";
{{/if}}
import type { ReactNode } from "react";
{{else}}
import type { Metadata } from "next";
import type { ReactNode } from "react";
{{/if}}

const title = "{{projectName}}";

export const metadata: Metadata = { description: "Next.js app", title };

interface RootLayoutProps {
  readonly children: ReactNode;
}

const RootLayout = ({ children }: RootLayoutProps) =>
{{#if useShadcn}}
(
  <html lang="en" suppressHydrationWarning>
    <body className={fonts}>
      <DesignSystemProvider>{children}</DesignSystemProvider>
    </body>
  </html>
);
{{else}}
(
  <html lang="en" suppressHydrationWarning>
    <body className="min-h-dvh antialiased">{children}</body>
  </html>
);
{{/if}}

export default RootLayout;
`],
    ["app/page.tsx", `const Home = () => (
  <main className="mx-auto flex min-h-dvh w-full max-w-2xl flex-col px-6 py-24 sm:py-32">
    <section className="grid gap-24">
      <header>
        <h1 className="font-serif text-3xl font-normal tracking-tight text-foreground sm:text-5xl">
          {{ projectName }}
        </h1>
        <p className="mt-1 text-muted-foreground">A Verno Studio starter.</p>
      </header>
      <div className="grid gap-5 text-pretty text-sm leading-7 text-muted-foreground sm:text-base">
        <p>
          A Verno Studio starter, shaped for taste, systems, and the first commit—so the surface is
          considered before the feature list runs long.
        </p>
        <p>
          Edit{" "}
          <code className="rounded border border-border bg-muted px-1.5 py-0.5 font-mono text-sm text-foreground">
            app/page.tsx
          </code>{" "}
          to get started.
        </p>
      </div>
    </section>
  </main>
);

export default Home;
`],
    ["components.json", `{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "{{componentsStyle}}",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "",
    "css": "app/globals.css",
    "baseColor": "neutral",
    "cssVariables": true,
    "prefix": ""
  },
  "iconLibrary": "lucide",
  "rtl": false,
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils",
    "ui": "@/components/ui",
    "lib": "@/lib",
    "hooks": "@/hooks"
  },
  "menuColor": "default",
  "menuAccent": "subtle",
  "registries": {
    "@vernostudio": "https://verno-studio.vercel.app/r/{name}.json"
  }
}
`],
    ["components/providers/client.tsx", `"use client";

import { ThemeProvider } from "next-themes";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner";
import type { PropsWithChildren } from "react";

export const DesignSystemProvider = ({ children }: PropsWithChildren) => (
  <ThemeProvider attribute="class" defaultTheme="system" disableTransitionOnChange enableSystem>
    <TooltipProvider delayDuration={0}>
      {children}
      <Toaster />
    </TooltipProvider>
  </ThemeProvider>
);
`],
    ["lib/fonts.ts", `import { cn } from "./utils";
import {
  Geist as createSans,
  Instrument_Serif as createSerif,
  Geist_Mono as createMono,
} from "next/font/google";

const sans = createSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const mono = createMono({
  subsets: ["latin"],
  variable: "--font-mono",
});

const serif = createSerif({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-serif",
  weight: "400",
});

export const fonts = cn(
  sans.variable,
  mono.variable,
  serif.variable,
  "touch-manipulation font-sans antialiased",
);
`],
    ["lib/utils.ts", `import { clsx } from "clsx";
import type { ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export const cn = (...inputs: ClassValue[]) => twMerge(clsx(inputs));
`],
    ["next.config.ts", `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  experimental: {
    turbopackFileSystemCacheForDev: true,
  },

  images: {
    formats: ["image/avif", "image/webp"],
  },
};

export default nextConfig;
`],
    ["package.json", `{
  "name": "{{#if turborepo}}web{{else}}{{projectName}}{{/if}}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "next build",
    "dev": "next dev{{#if turborepo}} --port 3000{{/if}}",
    "start": "next start",
    "typecheck": "next typegen && tsgo --noEmit"
  },
  "dependencies": {
{{#if hasDesignSystem}}    "{{dsName}}": "workspace:*"
{{/if}}  },
{{#if turborepo}}
  "devDependencies": {}
{{else}}
  "devDependencies": {},
  "packageManager": "{{packageManagerField}}"
{{/if}}
}
`],
    ["postcss.config.mjs", `const config = { plugins: { "@tailwindcss/postcss": {} } };
export default config;
`],
    ["tsconfig.json", `{{#if turborepo}}
  {{#if hasTypescriptConfigPackage}}
    { "extends": "../../packages/typescript-config/nextjs.json", "compilerOptions": { "paths": {
    "@/*": ["./*"], "@{{npmScope}}/*": ["../../packages/*"] } }, "include": [ "next-env.d.ts",
    "**/*.ts", "**/*.tsx", ".next/types/**/*.ts", ".next/dev/types/**/*.ts" ], "exclude":
    ["node_modules"] }
  {{else}}
    { "compilerOptions": { "target": "ES2017", "lib": ["dom", "dom.iterable", "esnext"], "allowJs":
    true, "skipLibCheck": true, "strict": true, "esModuleInterop": true, "module":
    "esnext", "moduleResolution": "bundler", "resolveJsonModule": true, "isolatedModules": true,
    "jsx": "react-jsx", "incremental": true, "plugins": [{ "name": "next" }], "paths": { "@/*":
    ["./*"] } }, "include": [ "next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts",
    ".next/dev/types/**/*.ts" ], "exclude": ["node_modules"] }
  {{/if}}
{{else}}
  { "compilerOptions": { "target": "ES2017", "lib": ["dom", "dom.iterable", "esnext"], "allowJs":
  true, "skipLibCheck": true, "strict": true, "esModuleInterop": true, "module":
  "esnext", "moduleResolution": "bundler", "resolveJsonModule": true, "isolatedModules": true,
  "jsx": "react-jsx", "incremental": true, "plugins": [{ "name": "next" }], "paths": { "@/*":
  ["./*"] } }, "include": [ "next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts",
  ".next/dev/types/**/*.ts" ], "exclude": ["node_modules"] }
{{/if}}`]
  ]),
  "addons/turborepo": new Map<string, string>([
    ["package.json", `{
  "name": "{{projectName}}",
  "private": true,
  "workspaces": ["apps/*", "packages/*"],
  "type": "module",
  "scripts": {
    "build": "turbo run build",
    "dev": "turbo run dev",
    "typecheck": "turbo run typecheck"
  },
  "devDependencies": {},
  "engines": {
    "node": ">=18"
  },
  "packageManager": "{{packageManagerField}}"
}
`],
    ["turbo.json", `{
  "$schema": "https://turborepo.dev/schema.json",
  "tasks": {
    "build": {
      "dependsOn": ["^build"],
      "inputs": ["$TURBO_DEFAULT$", ".env*"],
      "outputs": [".next/**", "!.next/cache/**", "dist/**"]
    },
    "typecheck": { "dependsOn": ["^typecheck"] },
    "dev": { "cache": false, "persistent": true }
  }
}
`]
  ]),
  "packages/design-system": new Map<string, string>([
    ["packages/design-system/components.json", `{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "{{componentsStyle}}",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "",
    "css": "styles/globals.css",
    "baseColor": "neutral",
    "cssVariables": true,
    "prefix": ""
  },
  "iconLibrary": "lucide",
  "rtl": false,
  "aliases": {
    "components": "{{dsName}}/components",
    "utils": "{{dsName}}/lib/utils",
    "ui": "{{dsName}}/components/ui",
    "lib": "{{dsName}}/lib",
    "hooks": "{{dsName}}/hooks"
  },
  "menuColor": "default",
  "menuAccent": "subtle",
  "registries": {
    "@vernostudio": "https://verno-studio.vercel.app/r/{name}.json"
  }
}
`],
    ["packages/design-system/components/providers/client.tsx", `"use client";

import { ThemeProvider } from "next-themes";
import { TooltipProvider } from "../ui/tooltip";
import { Toaster } from "../ui/sonner";
import type { PropsWithChildren } from "react";

export const DesignSystemProvider = ({ children }: PropsWithChildren) => (
  <ThemeProvider attribute="class" defaultTheme="system" disableTransitionOnChange enableSystem>
    <TooltipProvider delayDuration={0}>
      {children}
      <Toaster />
    </TooltipProvider>
  </ThemeProvider>
);
`],
    ["packages/design-system/lib/fonts.ts", `import { cn } from "./utils";
import {
  Geist as createSans,
  Instrument_Serif as createSerif,
  Geist_Mono as createMono,
} from "next/font/google";

const sans = createSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const mono = createMono({
  subsets: ["latin"],
  variable: "--font-mono",
});

const serif = createSerif({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-serif",
  weight: "400",
});

export const fonts = cn(
  sans.variable,
  mono.variable,
  serif.variable,
  "touch-manipulation font-sans antialiased",
);
`],
    ["packages/design-system/lib/utils.ts", `import { clsx } from "clsx";
import type { ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export const cn = (...inputs: ClassValue[]) => twMerge(clsx(inputs));
`],
    ["packages/design-system/package.json", `{
  "name": "{{dsName}}",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "sideEffects": false,
  "scripts": {
    "typecheck": "tsgo --noEmit"
  },
  "dependencies": {},
  "devDependencies": {},
  "peerDependencies": {}
}
`],
    ["packages/design-system/styles/globals.css", `@import "tailwindcss";
@import "tw-animate-css";
@import "shadcn/tailwind.css";

@custom-variant dark (&:is(.dark *));

@source "../../../**/*.{ts,tsx}";

/* The only raw values in this file. Everything below derives from them, so
   light and dark cannot drift apart, and re-theming means editing these two
   blocks and nothing else. Chromatic steps exist only where color carries
   meaning — focus, destructive, and the five chart series, which need hues a
   reader can tell apart. */
:root,
.light {
  color-scheme: light;

  --background-100: oklch(1 0 0);
  --background-200: oklch(0.984 0 0);
  --gray-100: oklch(0.961 0 0);
  --gray-200: oklch(0.94 0 0);
  --gray-300: oklch(0.925 0 0);
  --gray-400: oklch(0.937 0 0);
  --gray-500: oklch(0.836 0 0);
  --gray-600: oklch(0.732 0 0);
  --gray-700: oklch(0.65 0 0);
  --gray-800: oklch(0.59 0 0);
  --gray-900: oklch(0.42 0 0);
  --gray-1000: oklch(0.205 0 0);
  --gray-alpha-300: oklch(0 0 0 / 0.1);
  --gray-alpha-400: oklch(0 0 0 / 0.08);
  --gray-alpha-700: oklch(0 0 0 / 0.44);
  --blue-700: oklch(57.61% 0.2508 258.23);
  --red-700: oklch(62.56% 0.2524 23.03);
  --purple-700: oklch(55.5% 0.3008 306.12);
  --teal-700: oklch(64.92% 0.1572 181.95);
  --amber-700: oklch(81.87% 0.1969 76.46);
  --pink-700: oklch(63.52% 0.238 1.01);
  --shadow-tint: oklch(0 0 0 / 0.04);
}

.dark {
  color-scheme: dark;

  --background-100: oklch(0 0 0);
  --background-200: oklch(0.027 0 0);
  --gray-100: oklch(0.218 0 0);
  --gray-200: oklch(0.239 0 0);
  --gray-300: oklch(0.281 0 0);
  --gray-400: oklch(0.301 0 0);
  --gray-500: oklch(0.39 0 0);
  --gray-600: oklch(0.623 0 0);
  --gray-700: oklch(0.65 0 0);
  --gray-800: oklch(0.59 0 0);
  --gray-900: oklch(0.706 0 0);
  --gray-1000: oklch(0.946 0 0);
  --gray-alpha-300: oklch(1 0 0 / 0.13);
  --gray-alpha-400: oklch(1 0 0 / 0.14);
  --gray-alpha-700: oklch(1 0 0 / 0.54);
  --blue-700: oklch(71.7% 0.1648 250.794);
  --red-700: oklch(62.56% 0.2234 23.03);
  --purple-700: oklch(55.5% 0.2186 306.12);
  --teal-700: oklch(64.92% 0.1403 181.95);
  --amber-700: oklch(81.87% 0.1969 76.46);
  --pink-700: oklch(63.52% 0.2346 1.01);
  --shadow-tint: oklch(0 0 0 / 0.5);
}

/* The contract \`shadcn add\` writes against. Every value is a step from the
   scale above, so a generated component and a hand-written surface cannot
   disagree. */
:root {
  --background: var(--background-100);
  --foreground: var(--gray-1000);
  --card: var(--background-100);
  --card-foreground: var(--gray-1000);
  --popover: var(--background-100);
  --popover-foreground: var(--gray-1000);
  --primary: var(--gray-1000);
  --primary-foreground: var(--background-100);
  --secondary: var(--gray-100);
  --secondary-foreground: var(--gray-1000);
  --muted: var(--gray-100);
  --muted-foreground: var(--gray-900);
  --accent: var(--gray-200);
  --accent-foreground: var(--gray-1000);
  --destructive: var(--red-700);
  --destructive-foreground: oklch(1 0 0);
  --border: var(--gray-alpha-400);
  --border-strong: var(--gray-alpha-700);
  --input: var(--gray-alpha-400);
  --ring: var(--blue-700);

  /* \`shadcn add --all\` installs sidebar.tsx, which styles itself entirely
     through these. Tailwind omits a utility whose theme key is missing, so
     without them bg-sidebar and friends compile to nothing at all. Greys
     only — a sidebar is chrome, not content. */
  --sidebar: var(--background-100);
  --sidebar-foreground: var(--gray-1000);
  --sidebar-primary: var(--gray-1000);
  --sidebar-primary-foreground: var(--background-100);
  --sidebar-accent: var(--gray-200);
  --sidebar-accent-foreground: var(--gray-1000);
  --sidebar-border: var(--gray-alpha-400);
  --sidebar-ring: var(--blue-700);

  /* Series colors for chart.tsx. Spread around the wheel rather than ordered
     by the palette, so adjacent series stay distinguishable: 258° 306° 182°
     76° 1°. Red sits this one out — it means destructive everywhere else. */
  --chart-1: var(--blue-700);
  --chart-2: var(--purple-700);
  --chart-3: var(--teal-700);
  --chart-4: var(--amber-700);
  --chart-5: var(--pink-700);

  /* Two radii, nothing between them — a third value is where a scale starts
     to drift. */
  --radius-small: 0.375rem;
  --radius: 0.5rem;
}

@theme inline {
  --color-background-100: var(--background-100);
  --color-background-200: var(--background-200);
  --color-gray-100: var(--gray-100);
  --color-gray-200: var(--gray-200);
  --color-gray-300: var(--gray-300);
  --color-gray-400: var(--gray-400);
  --color-gray-500: var(--gray-500);
  --color-gray-600: var(--gray-600);
  --color-gray-700: var(--gray-700);
  --color-gray-800: var(--gray-800);
  --color-gray-900: var(--gray-900);
  --color-gray-1000: var(--gray-1000);

  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --color-card: var(--card);
  --color-card-foreground: var(--card-foreground);
  --color-popover: var(--popover);
  --color-popover-foreground: var(--popover-foreground);
  --color-primary: var(--primary);
  --color-primary-foreground: var(--primary-foreground);
  --color-secondary: var(--secondary);
  --color-secondary-foreground: var(--secondary-foreground);
  --color-muted: var(--muted);
  --color-muted-foreground: var(--muted-foreground);
  --color-accent: var(--accent);
  --color-accent-foreground: var(--accent-foreground);
  --color-destructive: var(--destructive);
  --color-destructive-foreground: var(--destructive-foreground);
  --color-border: var(--border);
  --color-border-strong: var(--border-strong);
  --color-input: var(--input);
  --color-ring: var(--ring);

  --color-sidebar: var(--sidebar);
  --color-sidebar-foreground: var(--sidebar-foreground);
  --color-sidebar-primary: var(--sidebar-primary);
  --color-sidebar-primary-foreground: var(--sidebar-primary-foreground);
  --color-sidebar-accent: var(--sidebar-accent);
  --color-sidebar-accent-foreground: var(--sidebar-accent-foreground);
  --color-sidebar-border: var(--sidebar-border);
  --color-sidebar-ring: var(--sidebar-ring);

  --color-chart-1: var(--chart-1);
  --color-chart-2: var(--chart-2);
  --color-chart-3: var(--chart-3);
  --color-chart-4: var(--chart-4);
  --color-chart-5: var(--chart-5);

  /* 4px steps, so spacing lands on 4 8 12 16 20 24 32 40 48 64. */
  --spacing: 0.25rem;

  /* sm and md collapse onto the small step so the scale cannot drift into a
     third value. */
  --radius-sm: var(--radius-small);
  --radius-md: var(--radius-small);
  --radius-lg: var(--radius);

  /* Elevation earns a hairline first and depth only when something floats. */
  --shadow-border: 0 0 0 1px var(--border);
  --shadow-xs: 0 1px 2px 0 var(--shadow-tint);
  --shadow-sm: 0 2px 4px 0 var(--shadow-tint);
  --shadow-md: 0 4px 8px 0 var(--shadow-tint);
  --shadow-lg: 0 8px 16px 0 var(--shadow-tint);

  /* One slot per type role, so \`text-*\` cannot produce a size that isn't a
     role. */
  --text-xs: 0.8125rem; /* label, metadata */
  --text-xs--line-height: 1.125rem;
  --text-sm: 0.875rem; /* compact */
  --text-sm--line-height: 1.25rem;
  --text-base: 1rem; /* body */
  --text-base--line-height: 1.5rem;
  --text-lg: 1.125rem; /* lede */
  --text-lg--line-height: 1.75rem;
  --text-xl: 1.25rem; /* heading-20 */
  --text-xl--line-height: 1.625rem;
  --text-xl--letter-spacing: -0.02em;
  --text-2xl: 1.5rem; /* heading-24 */
  --text-2xl--line-height: 2rem;
  --text-2xl--letter-spacing: -0.04em;
  --text-3xl: 2rem; /* title */
  --text-3xl--line-height: 2.5rem;
  --text-3xl--letter-spacing: -0.06em;
  --text-4xl: 2.5rem; /* page title */
  --text-4xl--line-height: 3rem;
  --text-4xl--letter-spacing: -0.06em;
  --text-5xl: 3rem; /* display */
  --text-5xl--line-height: 3.5rem;
  --text-5xl--letter-spacing: -0.06em;

  --font-weight-heading: 450;
  --tracking-tighter: -0.06em;
  --tracking-tight: -0.04em;
  --tracking-snug: -0.02em;
}
`],
    ["packages/design-system/tsconfig.json", `{
  "extends": "../typescript-config/react-library.json",
  "compilerOptions": {
    "paths": {
      "@/*": ["./*"],
      "{{dsName}}/*": ["./*"]
    }
  },
  "include": [
    "components/**/*.ts",
    "components/**/*.tsx",
    "lib/**/*.ts",
    "hooks/**/*.ts",
    "src/**/*.ts",
    "src/**/*.tsx"
  ],
  "exclude": ["node_modules"]
}
`]
  ]),
  "packages/typescript-config": new Map<string, string>([
    ["packages/typescript-config/base.json", `{
  "$schema": "https://json.schemastore.org/tsconfig",
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "strictNullChecks": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "incremental": true
  },
  "exclude": ["node_modules"]
}
`],
    ["packages/typescript-config/nextjs.json", `{
  "$schema": "https://json.schemastore.org/tsconfig",
  "extends": "./base.json",
  "compilerOptions": {
    "plugins": [{ "name": "next" }]
  }
}
`],
    ["packages/typescript-config/package.json", `{
  "name": "{{tsConfigName}}",
  "version": "0.0.0",
  "private": true,
  "license": "MIT",
  "files": [
    "base.json",
    "nextjs.json",
    "react-library.json"
  ]
}
`],
    ["packages/typescript-config/react-library.json", `{
  "$schema": "https://json.schemastore.org/tsconfig",
  "extends": "./base.json",
  "compilerOptions": { "jsx": "react-jsx" }
}
`]
  ])
} as const satisfies Record<string, ReadonlyMap<string, string>>;

