import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { LAYERS, toLayerOutputKey } from "../src/layers/registry";

const here = import.meta.dirname;
const packageRoot = path.resolve(here, "..");
const templatesDir = path.join(packageRoot, "templates");
const outFile = path.join(packageRoot, "src", "templates.generated.ts");

const listEntriesRecursive = async (dir: string, base: string): Promise<readonly string[]> => {
  const out: string[] = [];
  const entries = await readdir(dir, { withFileTypes: true });
  for (const e of entries) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) {
      // oxlint-disable-next-line no-await-in-loop -- sequential by design
      out.push(...(await listEntriesRecursive(full, base)));
    } else {
      out.push(path.relative(base, full));
    }
  }
  return out;
};

const escapeTemplateLiteral = (content: string): string =>
  content.replaceAll("\\", "\\\\").replaceAll("`", "\\`").replaceAll("${", "\\${");

const run = async (): Promise<void> => {
  const layerBlocks: string[] = [];
  let totalFiles = 0;

  for (const { id: layerId } of LAYERS) {
    const abs = path.join(templatesDir, layerId);
    try {
      // oxlint-disable-next-line no-await-in-loop -- sequential by design
      await readdir(abs);
    } catch {
      continue;
    }
    // oxlint-disable-next-line no-await-in-loop -- sequential by design
    const rels = await listEntriesRecursive(abs, abs);
    const entries: string[] = [];
    for (const rel of [...rels].toSorted((a, b) => a.localeCompare(b))) {
      const fullPath = path.join(abs, rel);
      const outputKey = toLayerOutputKey(layerId, rel);
      // oxlint-disable-next-line no-await-in-loop -- sequential by design
      const content = await readFile(fullPath, "utf-8");
      const escaped = escapeTemplateLiteral(content);
      entries.push(`    ["${outputKey}", \`${escaped}\`]`);
    }
    totalFiles += entries.length;
    layerBlocks.push(`  "${layerId}": new Map<string, string>([\n${entries.join(",\n")}\n  ])`);
  }

  const body = `/* eslint-disable max-lines */
/* This file is generated by scripts/generate-template-registry.ts — do not edit by hand. */

export const TEMPLATE_COUNT = ${String(totalFiles)} as const;

export const EMBEDDED_BY_LAYER = {
${layerBlocks.join(",\n")}
} as const satisfies Record<string, ReadonlyMap<string, string>>;
`;

  await writeFile(outFile, `${body}\n`, "utf-8");
};

await run();
