import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";

const here = import.meta.dirname;
const packageRoot = resolve(here, "..");
const templatesDir = join(packageRoot, "templates");
const outFile = join(packageRoot, "src", "templates.generated.ts");

const listEntriesRecursive = async (dir: string, base: string): Promise<readonly string[]> => {
  const out: string[] = [];
  const entries = await readdir(dir, { withFileTypes: true });
  for (const e of entries) {
    const full = join(dir, e.name);
    if (e.isDirectory()) {
      out.push(...(await listEntriesRecursive(full, base)));
    } else {
      out.push(relative(base, full));
    }
  }
  return out;
};

const readTree = async (dir: string, base: string): Promise<Readonly<Record<string, string>>> => {
  const out: Record<string, string> = {};
  for (const rel of await listEntriesRecursive(dir, base)) {
    const p = join(base, rel);
    const key = rel.split("\\").join("/");
    out[key] = await readFile(p, "utf-8");
  }
  return out;
};

const mergeBundle = async (
  id: "next-app" | "next-turborepo",
): Promise<Readonly<Record<string, string>>> => {
  const sharedDir = join(templatesDir, "shared");
  const specDir = join(templatesDir, id);
  const shared = await readTree(sharedDir, sharedDir);
  const spec = await readTree(specDir, specDir);
  return { ...shared, ...spec };
};

const run = async (): Promise<void> => {
  const nextApp = await mergeBundle("next-app");
  const nextTurborepo = await mergeBundle("next-turborepo");
  const header = `/* eslint-disable max-lines */
/* This file is generated by scripts/generate-template-registry.ts — do not edit by hand. */
`;
  const body = `export const RAW_TEMPLATES = ${JSON.stringify(
    { "next-app": nextApp, "next-turborepo": nextTurborepo },
    null,
    2,
  )} as const;
`;
  await writeFile(outFile, `${header}\n${body}\n`, "utf-8");
};

await run();
