import type { ProjectConfig } from "../config";
import { editorConfig, gitignoreContent, packageManagerField } from "../shared-root";
import type { FileTree } from "../paths";
import { packageJsonString } from "./strings";

export const buildNextAppTree = (config: ProjectConfig): FileTree => {
  const { projectName, packageManager, npmScope } = config;
  return {
    ".editorconfig": editorConfig,
    ".gitignore": gitignoreContent,
    "README.md": `# ${projectName}

Generated by @verno/cli (template: next-app, scope: @${npmScope}).
Run \`shadcn\` and \`ultracite\` post-hooks after create if you skipped them.
`,
    "app/globals.css": `@import "tailwindcss";
`,
    "app/layout.tsx": `import "./globals.css";
import type { Metadata } from "next";
import type { ReactNode } from "react";

const title = "${projectName}";

export const metadata: Metadata = { title, description: "Next.js app" };

const RootLayout = ({ children }: { readonly children: ReactNode }) => (
  <html lang="en" suppressHydrationWarning>
    <body className="antialiased min-h-dvh">
      {children}
    </body>
  </html>
);

export default RootLayout;
`,
    "app/page.tsx": `const Home = () => (
  <main className="mx-auto flex min-h-dvh max-w-2xl flex-col justify-center gap-4 px-4 py-16">
    <h1 className="text-3xl font-semibold tracking-tight">${projectName}</h1>
    <p className="text-neutral-600">Edit <code className="rounded bg-neutral-100 px-1.5 py-0.5 text-sm dark:bg-neutral-800">app/page.tsx</code> to get started.</p>
  </main>
);

export default Home;
`,
    "next-env.d.ts": `/// <reference types="next" />
/// <reference types="next/image-types/global" />
`,
    "next.config.ts": `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: { formats: ["image/avif", "image/webp"] },
};

export default nextConfig;
`,
    "package.json": packageJsonString({
      dependencies: {},
      devDependencies: {},
      name: projectName,
      packageManager: packageManagerField(packageManager),
      private: true,
      scripts: {
        build: "next build",
        dev: "next dev --port 3000",
        format: "ultracite fix",
        lint: "ultracite check",
        start: "next start",
        typecheck: "tsc --noEmit",
      },
      type: "module",
      version: "0.1.0",
    }),
    "postcss.config.mjs": `const config = { plugins: { "@tailwindcss/postcss": {} } };
export default config;
`,
    "tsconfig.json": `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts", ".next/dev/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`,
  };
};
